- hosts: all

  tasks:
    
    - name: PM2 startup configuration (pm2 start)
      command: docker-compose up -d
      args:
        chdir: /home/bykea/superscript

    - name: Create PM2 service
      become: true
      command: env PATH=$PATH:/usr/bin pm2 startup upstart -u bykea --hp /home/bykea

    - git:
        repo: 'https://github.com/bykea/talos.git'
        dest: /home/bykea/github/talos
        version: master
   
    - name: Get updated files from git repository 
      git: 
        repo: "https://aleena995:iES3C&ZER4Ke@github.com/bykea/talos.git"
        dest: /home/bykea/github/talos

    - name: PM2 startup configuration (pm2 start)
      command: pm2 start 
      args:
        chdir: /home/bykea/github/talos

    - name: PM2 startup configuration (pm2 save)
      command: pm2 save

